import Header from "./components/Header";

export const metadata = {
  title: "Welcome to Yuki Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#f1efef] font-semibold">
        <Header />
        <div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
